steps:   
- name: gcr.io/cloud-builders/gcloud
  entrypoint: "bash"
  args: 
        - "-c"
        - |
          gcloud compute ssh --zone us-central1-a bss-uat-jump-host -- "curl -k https://deployer-service.telus-bss-uat.openshift.sdntest.netcracker.com"
timeout: 120s
options:
  logging: CLOUD_LOGGING_ONLY
  logStreamingOption: STREAM_ON
