steps:
  - name: gcr.io/cloud-builders/gcloud
    args:
        - "-c"
        - |
          for i in $(gcloud compute os-login ssh-keys list | grep -v FINGERPRINT); do echo $i; gcloud compute os-login ssh-keys remove --key $i; done
    entrypoint: bash
timeout: 120s
options:
  logStreamingOption: STREAM_ON
  logging: CLOUD_LOGGING_ONLY
