steps:
  - name: gcr.io/cloud-builders/gcloud
    args:
      - gcloud
      - compute
      - ssh
      - '--zone=us-central1-a'
      - bss-uat-jump-host
      - >-
        --command=curl -X POST https://builder-service.telus-bss-uat.openshift.sdntest.netcracker.com/generic-webhook-trigger/invoke?token=e0442a2026fa8839d3ee2aba0fbd76fd -H "Content-Type: application/json" -d "{"ref":"$_REF"}"
    entrypoint: bash
timeout: 120s
options:
  logStreamingOption: STREAM_ON
  logging: CLOUD_LOGGING_ONLY
